The token has not been saved to the git credentials helper. Pass `add_to_git_credential=True` in this function directly or `--add-to-git-credential` if using via `huggingface-cli` if you want to set the git credential as well.
Token is valid (permission: fineGrained).
Your token has been saved to /home/jeongseokoh/.cache/huggingface/token
Login successful
INFO 08-06 19:08:11 llm_engine.py:161] Initializing an LLM engine (v0.5.0.post1) with config: model='meta-llama/Meta-Llama-3-8B-Instruct', speculative_config=None, tokenizer='meta-llama/Meta-Llama-3-8B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, rope_scaling=None, rope_theta=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=8192, download_dir='../../hub/model/', load_format=LoadFormat.AUTO, tensor_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=auto, quantization_param_path=None, device_config=cuda, decoding_config=DecodingConfig(guided_decoding_backend='outlines'), seed=0, served_model_name=meta-llama/Meta-Llama-3-8B-Instruct)
INFO 08-06 19:08:15 weight_utils.py:218] Using model weights format ['*.safetensors']
INFO 08-06 19:08:19 model_runner.py:160] Loading model weights took 14.9595 GB
INFO 08-06 19:08:20 gpu_executor.py:83] # GPU blocks: 13407, # CPU blocks: 2048
INFO 08-06 19:08:24 model_runner.py:889] Capturing the model for CUDA graphs. This may lead to unexpected consequences if the model is not static. To run the model in eager mode, set 'enforce_eager=True' or use '--enforce-eager' in the CLI.
INFO 08-06 19:08:24 model_runner.py:893] CUDA graphs can take additional 1~3 GiB memory per GPU. If you are running out of memory, consider decreasing `gpu_memory_utilization` or enforcing eager mode. You can also reduce the `max_num_seqs` as needed to decrease memory usage.
INFO 08-06 19:08:34 model_runner.py:965] Graph capturing finished in 10 secs.
Model: llama3_8b is selected
Dataset: gsm8k is selected
Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]Processed prompts: 100%|██████████| 1/1 [00:04<00:00,  4.32s/it, est. speed input: 215.03 toks/s, output: 293.72 toks/s]Processed prompts: 100%|██████████| 1/1 [00:04<00:00,  4.32s/it, est. speed input: 215.03 toks/s, output: 293.72 toks/s]
Second job: 4.358040357008576 sec
Processed prompts:   0%|          | 0/5 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]Processed prompts:  20%|██        | 1/5 [00:00<00:02,  1.38it/s, est. speed input: 1468.01 toks/s, output: 11.06 toks/s]Processed prompts: 100%|██████████| 5/5 [00:00<00:00,  6.91it/s, est. speed input: 7301.09 toks/s, output: 55.27 toks/s]
Last job: 0.7376933309715241 sec
[rank0]: Traceback (most recent call last):
[rank0]:   File "/data2/jeongseokoh/jeongseokoh/inter_SC/inter_SC.py", line 829, in <module>
[rank0]:     main()
[rank0]:   File "/data2/jeongseokoh/jeongseokoh/inter_SC/inter_SC.py", line 814, in main
[rank0]:     results = parallel_process(context=c_dataset, question=q_dataset, answer=a_dataset, option=o_dataset, cot_ex=cot_ex, model=model, model_name=selected_model, dataset=selected_dataset)
[rank0]:   File "/data2/jeongseokoh/jeongseokoh/inter_SC/inter_SC.py", line 443, in parallel_process
[rank0]:     original_answer_completion = get_completion(context=c, question=q, choices=o, cot_ex=cot_ex, model=model, model_name=model_name, dataset=dataset)
[rank0]:   File "/data2/jeongseokoh/jeongseokoh/inter_SC/inter_SC.py", line 272, in get_completion
[rank0]:     for i, j in enumerate(0,len(completion), n_output_per_one):
[rank0]: TypeError: enumerate() takes at most 2 arguments (3 given)
srun: error: n02: task 0: Exited with exit code 1
